# To use this, install the python package `pre-commit` and
# run once `pre-commit install`. This will setup a git pre-commit-hook
# that is executed on each commit and will report the linting problems.
# To run all hooks on all files use `pre-commit run -a`

repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: Rust Format
        language: system
        entry: bash -c "cargo +stable fmt --all -- --check"
        files: ^.*\.rs$
        types:
          - file
          - rust
  - repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.3
    hooks:
     - id: detect-aws-credentials
     - id: end-of-file-fixer
     - id: check-merge-conflict
     - id: trailing-whitespace